version: 0.2

phases:
  install:
    commands:
      - echo "Installing dependencies (none needed for static HTML)..."
  build:
    commands:
      - echo "Building project..."
      - mkdir -p output
      - cp -r * output/
  post_build:
    commands:
      - echo "Build completed successfully!"

artifacts:
  files:
    - '**/*'
  base-directory: output
